"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MessageRole(str, Enum):
    r"""An enumeration."""
    USER = 'user'
    ASSISTANT = 'assistant'
    SYSTEM = 'system'
