"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MessageType(str, Enum):
    r"""An enumeration."""
    MESSAGE = 'message'
    SUMMARY = 'summary'
    FILTER = 'filter'
    TAG = 'tag'
