"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ShippingAttribute(str, Enum):
    r"""An enumeration."""
    FREE_SHIPPING = 'free_shipping'
    ONE_DAY_SHIPPING = 'one_day_shipping'
    TWO_DAY_SHIPPING = 'two_day_shipping'
    IN_STORE_PICKUP = 'in_store_pickup'
