"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import error as components_error
from ...models.components import pet as components_pet
from typing import Optional


@dataclasses.dataclass
class ShowPetByIDRequest:
    pet_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': False }})
    r"""The id of the pet to retrieve"""
    



@dataclasses.dataclass
class ShowPetByIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    error: Optional[components_error.Error] = dataclasses.field(default=None)
    r"""unexpected error"""
    pet: Optional[components_pet.Pet] = dataclasses.field(default=None)
    r"""Expected response to a valid request"""
    

