"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ClientDetailsTypedDict(TypedDict):
    ip: str
    user_agent: NotRequired[str]


class ClientDetails(BaseModel):
    ip: str

    user_agent: Optional[str] = None
