"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taggedlink import TaggedLink, TaggedLinkTypedDict
from ionic_api_sdk.types import BaseModel
from typing import Any, Optional, TypedDict
from typing_extensions import NotRequired


class EnrichedProductTypedDict(TypedDict):
    links: TaggedLinkTypedDict
    extensions: NotRequired[Any]
    reference_id: NotRequired[str]
    

class EnrichedProduct(BaseModel):
    links: TaggedLink
    extensions: Optional[Any] = None
    reference_id: Optional[str] = None
    
