"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ExtensionImagesTypedDict(TypedDict):
    thumbnail: NotRequired[str]
    

class ExtensionImages(BaseModel):
    thumbnail: Optional[str] = None
    
