"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ExtensionLinksTypedDict(TypedDict):
    original: NotRequired[str]
    tagged: NotRequired[str]
    

class ExtensionLinks(BaseModel):
    original: Optional[str] = None
    tagged: Optional[str] = None
    
