"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extensionimages import ExtensionImages, ExtensionImagesTypedDict
from .extensionlinks import ExtensionLinks, ExtensionLinksTypedDict
from .pricewithcurrency import PriceWithCurrency, PriceWithCurrencyTypedDict
from .shippingattribute import ShippingAttribute
from ionic_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ExtensionObjectTypedDict(TypedDict):
    images: ExtensionImagesTypedDict
    links: ExtensionLinksTypedDict
    price: PriceWithCurrencyTypedDict
    title: str
    shipping_attributes: NotRequired[List[ShippingAttribute]]


class ExtensionObject(BaseModel):
    images: ExtensionImages

    links: ExtensionLinks

    price: PriceWithCurrency

    title: str

    shipping_attributes: Optional[List[ShippingAttribute]] = None
