"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extensionobject import ExtensionObject, ExtensionObjectTypedDict
from ionic_api_sdk.types import BaseModel
from typing import List, TypedDict


class ExtensionTypedDict(TypedDict):
    data: List[ExtensionObjectTypedDict]
    

class Extension(BaseModel):
    data: List[ExtensionObject]
    
