"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extension import Extension, ExtensionTypedDict
from ionic_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class ExtensionsTypedDict(TypedDict):
    merchants: ExtensionTypedDict


class Extensions(BaseModel):
    merchants: Extension
