"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagerole import MessageRole
from .messagetype import MessageType
from ionic_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class MessageTypedDict(TypedDict):
    content: str
    role: MessageRole
    r"""An enumeration."""
    type: MessageType
    r"""An enumeration."""


class Message(BaseModel):
    content: str

    role: MessageRole
    r"""An enumeration."""

    type: MessageType
    r"""An enumeration."""
