"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import TypedDict


class PriceWithCurrencyTypedDict(TypedDict):
    amount: int
    currency: str
    

class PriceWithCurrency(BaseModel):
    amount: int
    currency: str
    
