"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .enrichedproduct import EnrichedProduct, EnrichedProductTypedDict
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ProductLinkResponseTypedDict(TypedDict):
    id: str
    product: EnrichedProductTypedDict
    idempotency_key: NotRequired[str]
    reference_id: NotRequired[str]
    

class ProductLinkResponse(BaseModel):
    id: str
    product: EnrichedProduct
    idempotency_key: Optional[str] = None
    reference_id: Optional[str] = None
    
