"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientdetails import ClientDetails, ClientDetailsTypedDict
from .productdetails import ProductDetails, ProductDetailsTypedDict
from .querydetails import QueryDetails, QueryDetailsTypedDict
from .userdetails import UserDetails, UserDetailsTypedDict
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ProductLinkRequestTypedDict(TypedDict):
    client_details: ClientDetailsTypedDict
    product: ProductDetailsTypedDict
    query: QueryDetailsTypedDict
    user_details: UserDetailsTypedDict
    idempotency_key: NotRequired[str]
    log_only: NotRequired[bool]
    reference_id: NotRequired[str]
    

class ProductLinkRequest(BaseModel):
    client_details: ClientDetails
    product: ProductDetails
    query: QueryDetails
    user_details: UserDetails
    idempotency_key: Optional[str] = None
    log_only: Optional[bool] = False
    reference_id: Optional[str] = None
    
