"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extensions import Extensions, ExtensionsTypedDict
from .link import Link, LinkTypedDict
from .shippingattribute import ShippingAttribute
from ionic_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ProductTypedDict(TypedDict):
    links: List[LinkTypedDict]
    merchant_name: str
    merchant_product_id: str
    name: str
    price: str
    status: str
    brand_name: NotRequired[str]
    description: NotRequired[str]
    extensions: NotRequired[ExtensionsTypedDict]
    merchant_logo: NotRequired[str]
    reference_url: NotRequired[str]
    shipping_attributes: NotRequired[List[ShippingAttribute]]
    thumbnail: NotRequired[str]
    upc: NotRequired[str]


class Product(BaseModel):
    links: List[Link]

    merchant_name: str

    merchant_product_id: str

    name: str

    price: str

    status: str

    brand_name: Optional[str] = None

    description: Optional[str] = None

    extensions: Optional[Extensions] = None

    merchant_logo: Optional[str] = None

    reference_url: Optional[str] = None

    shipping_attributes: Optional[List[ShippingAttribute]] = None

    thumbnail: Optional[str] = None

    upc: Optional[str] = None
