"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amountwithcurrency import AmountWithCurrency, AmountWithCurrencyTypedDict
from .productidentifiers import ProductIdentifiers, ProductIdentifiersTypedDict
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ProductDetailsTypedDict(TypedDict):
    identifiers: ProductIdentifiersTypedDict
    link: str
    image_url: NotRequired[str]
    price: NotRequired[AmountWithCurrencyTypedDict]
    reference_id: NotRequired[str]
    title: NotRequired[str]
    

class ProductDetails(BaseModel):
    identifiers: ProductIdentifiers
    link: str
    image_url: Optional[str] = None
    price: Optional[AmountWithCurrency] = None
    reference_id: Optional[str] = None
    title: Optional[str] = None
    
