"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ProductIdentifiersTypedDict(TypedDict):
    asin: NotRequired[str]
    ean: NotRequired[str]
    gtin: NotRequired[str]
    isbn: NotRequired[str]
    sku: NotRequired[str]
    tcin: NotRequired[str]
    upc: NotRequired[str]
    

class ProductIdentifiers(BaseModel):
    asin: Optional[str] = None
    ean: Optional[str] = None
    gtin: Optional[str] = None
    isbn: Optional[str] = None
    sku: Optional[str] = None
    tcin: Optional[str] = None
    upc: Optional[str] = None
    
