"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .product import Product, ProductTypedDict
from .query import Query, QueryTypedDict
from ionic_api_sdk.types import BaseModel
from typing import List, TypedDict


class QueryResultTypedDict(TypedDict):
    products: List[ProductTypedDict]
    query: QueryTypedDict
    

class QueryResult(BaseModel):
    products: List[Product]
    query: Query
    
