"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .queryresult import QueryResult, QueryResultTypedDict
from ionic_api_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class QueryAPIResponseTypedDict(TypedDict):
    token: str
    results: NotRequired[List[QueryResultTypedDict]]
    

class QueryAPIResponse(BaseModel):
    token: str
    results: Optional[List[QueryResult]] = None
    
