"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class QueryTypedDict(TypedDict):
    query: str
    max_price: NotRequired[int]
    min_price: NotRequired[int]
    num_results: NotRequired[int]


class Query(BaseModel):
    query: str

    max_price: Optional[int] = None

    min_price: Optional[int] = None

    num_results: Optional[int] = 5
