"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import TypedDict


class QueryDetailsTypedDict(TypedDict):
    q: str


class QueryDetails(BaseModel):
    q: str
