"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .message import Message, MessageTypedDict
from .query import Query, QueryTypedDict
from .session import Session, SessionTypedDict
from ionic_api_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class QueryAPIRequestTypedDict(TypedDict):
    query: QueryTypedDict
    messages: NotRequired[List[MessageTypedDict]]
    session: NotRequired[SessionTypedDict]


class QueryAPIRequest(BaseModel):
    query: Query

    messages: Optional[List[Message]] = None

    session: Optional[Session] = None
