"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class SessionTypedDict(TypedDict):
    locale: NotRequired[str]
    session_id: NotRequired[str]
    user_id: NotRequired[str]


class Session(BaseModel):
    locale: Optional[str] = "en-US"

    session_id: Optional[str] = None

    user_id: Optional[str] = None
