"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import TypedDict


class TaggedLinkTypedDict(TypedDict):
    original: str
    tagged: str


class TaggedLink(BaseModel):
    original: str

    tagged: str
