"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ionic_api_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UserDetailsTypedDict(TypedDict):
    email: str
    id: str
    postal_code: NotRequired[str]
    

class UserDetails(BaseModel):
    email: str
    id: str
    postal_code: Optional[str] = None
    
